### ISSUE TITLE
vite 现在是不是跑不起来antd了

### ISSUE THREAD

**Issue by mylesio** [hzyhbk/react-antd-vite-template#1]
老哥我down了你的项目，跑不起来了。你最近有研究vite和antd吗

**Comment by hzyhbk** [comment]
> 老哥我down了你的项目，跑不起来了。你最近有研究vite和antd吗

有段时间没玩了，我下午有空看下哈～

**Comment by hzyhbk** [comment]
@Boyceman 我跑了下没问题呀？我使用yarn安装依赖的。

**Comment by mylesio** [comment]
项目起得来，但是console会报错，我给你整个图

![image](https://user-images.githubusercontent.com/8738779/94633240-4efc3680-02ff-11eb-997c-c7a4062c136e.png)

**Comment by hzyhbk** [comment]
发现问题了，是vite版本导致的，把vite版本固定到1.0.0-beta.8

**Comment by hzyhbk** [comment]
经测试，1.0.0-rc.1是没问题的，再高的版本就开始报错了。
